### ISSUE TITLE
Don’t improve, reinvent it and the way we define it.

### ISSUE THREAD

**Issue by dlabz** [buildingSMART/IFC_UML#10]
Let’s start by the fact that I can’t even read the schema file on my up to date phone. 

Today’s standard is using emulators to define and test API schemas, that generate implementations from much cleaner code than xml. 

One standard that comes to mind is [RCF2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html) 

Have a interactive visual representation of the schema, to help think about the nD model, with focus on lossless projection of the diagram to lower dimensional spaces, and visual cues of impact to core values we strive to.

Define said core values. 

Think in terms of interactions between parties, and data flow, not in terms of model. Keep historical (bureaucratic and cultural) implementation of the proposal in mind, for reference and fun. 

Have a structured process of arriving to conclusions, as our target user is most likely to be an AI.

**Comment by berlotti** [comment]
Sorry, this is not according to the guidelines on https://github.com/buildingSMART/NextGen-IFC/wiki/Towards-a-technology-independent-IFC
