### ISSUE TITLE
UML/SysML + Modelica + STEP AP 242

### ISSUE THREAD

**Issue by EAzari** [buildingSMART/IFC_UML#11]
I think we can categorize the IFC data in three-four categories:
1. **Explicit** properties: Direct and explicit
2. **Implicit** properties: Indirectly
3. **Derived** (Derived Data, Derived Rules, ...)
4. **Inverse** (Connectors)

- A. And I think **UML/SysML** is/are good bases to develop the IFC, especially have the ability to be expanded 
- B. Also, Modelica can help IFC a lot, especially in Emulation, Simulation, and Analysis areas
(There's a SysML4Modelica as well)
- C. STEP AP 242 somewhat solved the challenges in the PLM area and could be a good reference to develop IFC, especially in Geometry/Topology area

The geometry/topology is the main part

**Comment by berlotti** [comment]
This issue is not according to the guidelines
