### ISSUE TITLE
Is IfcRail really building element? Is it a "part of the construction of a built facility"?

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/IFC_UML#62]
Is IfcRail really building element? Is it a "part of the construction of a built facility"?

**Comment by TLiebich** [comment]
The current abstract entity IfcBuildingElement was changed in IFC4.3 to an IfcBuiltElement and has the semantic of any part of a built facility. A railway line is a built facility.

The background was to avoid having elements, such as walls, members, etc. that can be part of any built facility (building, bridge, tunnel, harbor, etc.) being duplicated unter different parant classes (IfcBuildingElement, IfcBridgeElement, ...).
