### ISSUE TITLE
Change IfcPolygonalBoundedHalfSpace.PolygonalBoundary type to IfcIndexedPolyCurve

### ISSUE THREAD

**Issue by claimred** [buildingSMART/IFC_UML#70]
Description of the proposal:

https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcpolygonalboundedhalfspace.htm

`IfcPolygonalBoundedHalfSpace.PolygonalBoundary` attribute in the last version of IFC schema with every formal and informal proposition combined equals to closed 2d `IfcIndexedPolyCurve` with extra steps. Moreover, the informal proposition "(having a BasisCurve of type IfcLine, or IfcCircle)" is already baked in `IfcIndexedPolyCurve`.

What do we win:

- Simplification
- Removal of another use case for IfcPolyLine/IfcTrimmedCurve (https://github.com/buildingSMART/NextGen-IFC/issues/58)
- Possibly write an EXP function to set closed curve formal proposition

What do we lose

- Flexibility to allow complex curves for PolygonalBoundary later on?

Schema impact:

- Changing 

```diff
WHERE
  BoundaryDim : PolygonalBoundary.Dim = 2;
  BoundaryType : SIZEOF(TYPEOF(PolygonalBoundary) * [
-'IFCGEOMETRYRESOURCE.IfcPolyline',
-'IFCGEOMETRYRESOURCE.IfcCompositeCurve']
+'IFCGEOMETRYRESOURCE.IfcIndexedPolyCurve']
) = 1;
```

Backward compatible: 

- No

Automatic migration possible: 

- Yes

**Comment by berlotti** [comment]
Wow! Very nice catch.

**Comment by claimred** [comment]
Will be fixed here https://github.com/buildingSMART/IFC4.3.x-development/issues/198
