### ISSUE TITLE
IFC Spec

### ISSUE THREAD

**Issue by EAzari** [buildingSMART/IFC_UML#76]
It would be better if further IFC X specs include the "`Optional`" column in Attribute tables (Attribute definitions and Attribute inheritance)

Currently, tables have these columns:
- `#`
- `Attribute`
- `Type`
- `Cardinality`
- `Description`
- `G`

**Comment by pjanck** [comment]
`Optional` is denoted by `?` in the `Cardinality` column.

**Comment by EAzari** [comment]
@pjanck thanks Stefan, yes, however, I think `Cardinality` is related to sets and grouping, and it'd better have a separate column for `Optional`
If you think it doesn't cause misunderstanding, we can continue that way

**Comment by pjanck** [comment]
I understand your point. If you think a separate column would increase the readability of the documentation, you're welcome to contribute [here](https://github.com/buildingSMART/IfcDoc). I'm not sure which file needs to be adapted, but I'm sure you can figure it out :)

**Comment by berlotti** [comment]
This is not a NextGen issue.
